/* Generated By:JavaCC: Do not edit this line. ParamLoaderConstants.java */
package org.apache.pig.tools.parameters;

public interface ParamLoaderConstants {

  int EOF = 0;
  int LETTER = 5;
  int DIGIT = 6;
  int SPECIALCHAR = 7;
  int IDENTIFIER = 8;
  int ORD_LINE = 9;
  int LITERAL = 10;
  int SHELLCMD = 11;
  int EQUALS = 12;
  int COMMENT = 13;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIALCHAR>",
    "<IDENTIFIER>",
    "<ORD_LINE>",
    "<LITERAL>",
    "<SHELLCMD>",
    "\"=\"",
    "<COMMENT>",
  };

}
