/* Generated By:JJTree: Do not edit this line. C:\Users\Grant\Development\workspace\lilwall\Android\pig-branch-0.1\src-gen\org\apache\pig\impl\logicalLayer\parser\QueryParserTreeConstants.java */

package org.apache.pig.impl.logicalLayer.parser;

public interface QueryParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTSPLITCLAUSE = 1;
  public int JJTEXPR = 2;
  public int JJTNESTEDEXPR = 3;
  public int JJTALIAS = 4;
  public int JJTBASEEXPR = 5;
  public int JJTLOADCLAUSE = 6;
  public int JJTSTRINGLIST = 7;
  public int JJTFILENAME = 8;
  public int JJTFILTERCLAUSE = 9;
  public int JJTPCOND = 10;
  public int JJTPORCOND = 11;
  public int JJTPANDCOND = 12;
  public int JJTPUNARYCOND = 13;
  public int JJTPNOTCOND = 14;
  public int JJTCOGROUPCLAUSE = 15;
  public int JJTGROUPITEM = 16;
  public int JJTORDERCLAUSE = 17;
  public int JJTCROSSCLAUSE = 18;
  public int JJTJOINCLAUSE = 19;
  public int JJTUNIONCLAUSE = 20;
  public int JJTFOREACHCLAUSE = 21;
  public int JJTNESTEDBLOCK = 22;
  public int JJTNESTEDCOMMAND = 23;
  public int JJTNESTEDFILTER = 24;
  public int JJTNESTEDSORTORARRANGE = 25;
  public int JJTNESTEDDISTINCT = 26;
  public int JJTGENERATESTATEMENT = 27;
  public int JJTFLATTENEDGENERATEITEMLIST = 28;
  public int JJTFLATTENEDGENERATEITEM = 29;
  public int JJTINFIXEXPR = 30;
  public int JJTADDITIVEEXPR = 31;
  public int JJTMULTIPLICATIVEEXPR = 32;
  public int JJTUNARYEXPR = 33;
  public int JJTBASEEVALSPEC = 34;
  public int JJTBINCOND = 35;
  public int JJTFUNCEVALSPEC = 36;
  public int JJTEVALARGS = 37;
  public int JJTEVALARGSITEM = 38;
  public int JJTSCHEMA = 39;
  public int JJTATOMSCHEMA = 40;
  public int JJTSCHEMATUPLE = 41;
  public int JJTSCHEMABAG = 42;
  public int JJTTUPLESCHEMA = 43;
  public int JJTPWINDOW = 44;
  public int JJTPTIMEWINDOW = 45;
  public int JJTPTUPLEWINDOW = 46;
  public int JJTEVALFUNCTION = 47;
  public int JJTFILTERFUNCTION = 48;
  public int JJTVOID = 49;
  public int JJTBRACKETEDSIMPLEPROJ = 50;
  public int JJTSIMPLEPROJ = 51;
  public int JJTSIMPLEARGS = 52;
  public int JJTSIMPLEARGSITEM = 53;
  public int JJTSTAR = 54;
  public int JJTCONST = 55;
  public int JJTCOLORSPEC = 56;
  public int JJTDOLLARVAR = 57;
  public int JJTALIASFIELDORSPEC = 58;
  public int JJTSTREAMCLAUSE = 59;
  public int JJTCOMMAND = 60;
  public int JJTDEFINECLAUSE = 61;
  public int JJTSTORECLAUSE = 62;
  public int JJTPATHLIST = 63;
  public int JJTINPUTOUTPUTSPEC = 64;
  public int JJTCOMMANDSTREAM = 65;
  public int JJTERRORSPEC = 66;


  public String[] jjtNodeName = {
    "Parse",
    "SplitClause",
    "Expr",
    "NestedExpr",
    "Alias",
    "BaseExpr",
    "LoadClause",
    "StringList",
    "FileName",
    "FilterClause",
    "PCond",
    "POrCond",
    "PAndCond",
    "PUnaryCond",
    "PNotCond",
    "CogroupClause",
    "GroupItem",
    "OrderClause",
    "CrossClause",
    "JoinClause",
    "UnionClause",
    "ForEachClause",
    "NestedBlock",
    "NestedCommand",
    "NestedFilter",
    "NestedSortOrArrange",
    "NestedDistinct",
    "GenerateStatement",
    "FlattenedGenerateItemList",
    "FlattenedGenerateItem",
    "InfixExpr",
    "AdditiveExpr",
    "MultiplicativeExpr",
    "UnaryExpr",
    "BaseEvalSpec",
    "BinCond",
    "FuncEvalSpec",
    "EvalArgs",
    "EvalArgsItem",
    "Schema",
    "AtomSchema",
    "SchemaTuple",
    "SchemaBag",
    "TupleSchema",
    "PWindow",
    "PTimeWindow",
    "PTupleWindow",
    "EvalFunction",
    "FilterFunction",
    "void",
    "BracketedSimpleProj",
    "SimpleProj",
    "SimpleArgs",
    "SimpleArgsItem",
    "Star",
    "Const",
    "ColOrSpec",
    "DollarVar",
    "AliasFieldOrSpec",
    "StreamClause",
    "Command",
    "DefineClause",
    "StoreClause",
    "PathList",
    "InputOutputSpec",
    "CommandStream",
    "ErrorSpec",
  };
}
