/* Generated By:JJTree&JavaCC: Do not edit this line. QueryParserConstants.java */
package org.apache.pig.impl.logicalLayer.parser;

public interface QueryParserConstants {

  int EOF = 0;
  int STRFILTEROP = 7;
  int NUMFILTEROP = 8;
  int FILTEROP = 9;
  int DEFINE = 10;
  int LOAD = 11;
  int FILTER = 12;
  int FOREACH = 13;
  int MATCHES = 14;
  int ORDER = 15;
  int ARRANGE = 16;
  int DISTINCT = 17;
  int COGROUP = 18;
  int JOIN = 19;
  int CROSS = 20;
  int UNION = 21;
  int SPLIT = 22;
  int INTO = 23;
  int IF = 24;
  int ALL = 25;
  int ANY = 26;
  int AS = 27;
  int BY = 28;
  int USING = 29;
  int INNER = 30;
  int OUTER = 31;
  int STAR = 32;
  int PARALLEL = 33;
  int GROUP = 34;
  int AND = 35;
  int OR = 36;
  int NOT = 37;
  int CONTINUOUSLY = 38;
  int WINDOW = 39;
  int SECONDS = 40;
  int MINUTES = 41;
  int HOURS = 42;
  int TUPLES = 43;
  int GENERATE = 44;
  int FLATTEN = 45;
  int EVAL = 46;
  int STREAM = 47;
  int THROUGH = 48;
  int STORE = 49;
  int SHIP = 50;
  int CACHE = 51;
  int INPUT = 52;
  int OUTPUT = 53;
  int ERROR = 54;
  int STDIN = 55;
  int STDOUT = 56;
  int LIMIT = 57;
  int LETTER = 58;
  int DIGIT = 59;
  int SPECIALCHAR = 60;
  int FSSPECIALCHAR = 61;
  int IDENTIFIER = 62;
  int NUMBER = 63;
  int FLOAT = 64;
  int INTEGER = 65;
  int QUOTEDSTRING = 66;
  int EXECCOMMAND = 67;
  int DOLLARVAR = 68;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<STRFILTEROP>",
    "<NUMFILTEROP>",
    "<FILTEROP>",
    "\"define\"",
    "\"load\"",
    "\"filter\"",
    "\"foreach\"",
    "\"matches\"",
    "\"order\"",
    "\"arrange\"",
    "\"distinct\"",
    "\"cogroup\"",
    "\"join\"",
    "\"cross\"",
    "\"union\"",
    "\"split\"",
    "\"into\"",
    "\"if\"",
    "\"all\"",
    "\"any\"",
    "\"as\"",
    "\"by\"",
    "\"using\"",
    "\"inner\"",
    "\"outer\"",
    "\"*\"",
    "\"parallel\"",
    "\"group\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"continuously\"",
    "\"window\"",
    "\"seconds\"",
    "\"minutes\"",
    "\"hours\"",
    "\"tuples\"",
    "\"generate\"",
    "\"flatten\"",
    "\"eval\"",
    "\"stream\"",
    "\"through\"",
    "\"store\"",
    "\"ship\"",
    "\"cache\"",
    "\"input\"",
    "\"output\"",
    "\"stderr\"",
    "\"stdin\"",
    "\"stdout\"",
    "\"limit\"",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIALCHAR>",
    "<FSSPECIALCHAR>",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<QUOTEDSTRING>",
    "<EXECCOMMAND>",
    "<DOLLARVAR>",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\".\"",
    "\"#\"",
    "\"?\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"$\"",
  };

}
