/* Generated By:JavaCC: Do not edit this line. PigScriptParserConstants.java */
package org.apache.pig.tools.pigscript.parser;

public interface PigScriptParserConstants {

  int EOF = 0;
  int CAT = 5;
  int CD = 6;
  int COPY = 7;
  int COPYFROMLOCAL = 8;
  int COPYTOLOCAL = 9;
  int DUMP = 10;
  int DESCRIBE = 11;
  int EXPLAIN = 12;
  int HELP = 13;
  int KILL = 14;
  int LS = 15;
  int MOVE = 16;
  int MKDIR = 17;
  int PWD = 18;
  int QUIT = 19;
  int REGISTER = 20;
  int REMOVE = 21;
  int SET = 22;
  int ILLUSTRATE = 23;
  int SCRIPT_DONE = 24;
  int PIG = 60;
  int EOL = 61;
  int QUOTE = 62;
  int SEMICOLON = 63;
  int LETTER = 64;
  int DIGIT = 65;
  int SPECIALCHAR = 66;
  int FSSPECIALCHAR = 67;
  int FLOAT = 68;
  int INTEGER = 69;
  int NUMBER = 70;
  int IDENTIFIER = 71;
  int PATH = 72;
  int QUOTEDSTRING = 73;

  int DEFAULT = 0;
  int PIG_START = 1;
  int SINGLE_LINE_COMMENT = 2;
  int MULTI_LINE_COMMENT = 3;
  int IN_STRING = 4;
  int IN_COMMAND = 5;
  int IN_BLOCK = 6;
  int PIG_END = 7;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "\"cat\"",
    "\"cd\"",
    "\"cp\"",
    "\"copyFromLocal\"",
    "\"copyToLocal\"",
    "\"dump\"",
    "\"describe\"",
    "\"explain\"",
    "\"help\"",
    "\"kill\"",
    "\"ls\"",
    "\"mv\"",
    "\"mkdir\"",
    "\"pwd\"",
    "\"quit\"",
    "\"register\"",
    "\"rm\"",
    "\"set\"",
    "\"illustrate\"",
    "\"scriptDone\"",
    "\"split\"",
    "\"define\"",
    "\"store\"",
    "<token of kind 28>",
    "\"\\\'\"",
    "\"`\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"--\"",
    "\"/*\"",
    "<token of kind 36>",
    "<token of kind 37>",
    "<token of kind 38>",
    "<token of kind 39>",
    "\"*/\"",
    "<token of kind 41>",
    "<token of kind 42>",
    "\"\\\\\\\'\"",
    "\"\\\'\"",
    "<token of kind 45>",
    "<token of kind 46>",
    "\"\\\\`\"",
    "\"`\"",
    "<token of kind 49>",
    "<token of kind 50>",
    "\"\\\"\"",
    "\"{\"",
    "<token of kind 53>",
    "\"\\\'\"",
    "\"`\"",
    "\"--\"",
    "\"/*\"",
    "<token of kind 58>",
    "<token of kind 59>",
    "\"\"",
    "<EOL>",
    "\"\\\'\"",
    "\";\"",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIALCHAR>",
    "<FSSPECIALCHAR>",
    "<FLOAT>",
    "<INTEGER>",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<PATH>",
    "<QUOTEDSTRING>",
  };

}
